<?php
/**
 * Created by PhpStorm.
 * User: mirza
 * Date: 7/20/18
 * Time: 4:24 PM
 */

namespace Model\Entity;


use Component\Collection;
use Model\Contract\HasId;

class SwapRequestCollection extends Collection
{

    public function buildEntity(): HasId
    {
        // TODO: Implement buildEntity() method.
    }


    public function addEntity(HasId $entity, $key = null)
    {
        return parent::addEntity($entity, $key); // TODO: Change the autogenerated stub
    }
}