parameters:
    pdo.error_attribute: !php/const PDO::ATTR_ERRMODE
    pdo.error_mode: !php/const PDO::ERRMODE_EXCEPTION

services:

    pdo:
        class: 'PDO'
        arguments: ['%database.dsn%','root','root']
        calls:
            - [setAttribute, ['%pdo.error_attribute%', '%pdo.error_mode%']]
           