# home
root:
    path: /
    defaults:
        resource: "landing"
    methods: [GET, POST]
    
swapp:
    path: /{resource}{slash}{action}
    requirements:
        resource: "swapp"
        slash: "[/]{0,1}"
    methods: [GET, POST, PUT, DELETE]
    