kind: Service
apiVersion: v1
metadata:
  name: swapper-swapps-backend-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    role: backend
    app: swapper-swapps